apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-devops-runners
  namespace: devops
spec:
  replicas: 1
  template:
    spec:
      repository: yurtseveronr/onur-master-thesis-data
      nodeSelector:
        node-type: devops
      containers:
        - name: runner
          image: ghcr.io/actions/actions-runner:latest
          env:
            - name: DOCKER_HOST
              value: "tcp://docker-daemon:2375"
            - name: RUNNER_ALLOW_RUNASROOT
              value: "1"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1000m"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
      volumes:
        - name: work
          emptyDir: {} 