
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: ai
  labels:
    app: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      serviceAccountName: ai-sa
      nodeSelector:
        node-type: services
      containers:
        - name: chatbot
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/chatbot-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          
          readinessProbe:
            tcpSocket: { port: 8091 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8091 }
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: ai
spec:
  type: ClusterIP
  selector:
    app: chatbot
  ports:
    - name: http
      port: 8091
      targetPort: 8091
