apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: services
  labels:
    app: authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      serviceAccountName: services-sa   # SA zaten mevcut
      nodeSelector:
        node-type: services
      containers:
        - name: authentication
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/authentication-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
    - name: http
      port: 5000
      targetPort: 5000
