apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: services
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: services-sa   # SA zaten mevcut
      nodeSelector:
        node-type: services
      containers:
        - name: frontend
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/frontend-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 8501
      targetPort: 8501
