apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  namespace: services
  labels:
    app: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      serviceAccountName: services-sa   # SA zaten mevcut
      nodeSelector:
        node-type: services
      containers:
        - name: user
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/movies-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: movies
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: movies
  ports:
    - name: http
      port: 8081
      targetPort: 8081
