apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: services
  labels:
    app: search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      serviceAccountName: services-sa   # SA zaten mevcut
      nodeSelector:
        node-type: services
      containers:
        - name: user
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/search-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      port: 8080
      targetPort: 8080
