apiVersion: apps/v1
kind: Deployment
metadata:
  name: series
  namespace: services
  labels:
    app: series
spec:
  replicas: 1
  selector:
    matchLabels:
      app: series
  template:
    metadata:
      labels:
        app: series
    spec:
      serviceAccountName: services-sa   # SA zaten mevcut
      nodeSelector:
        node-type: services
      containers:
        - name: series
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/series-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: series
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: series
  ports:
    - name: http
      port: 8082
      targetPort: 8082
