apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: services
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: services-sa   # SA zaten mevcut
      nodeSelector:
        node-type: services
      containers:
        - name: user
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: services
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: http
      port: 8080
      targetPort: 8080
