apiVersion: v1
kind: ServiceAccount
metadata:
  name: services-sa
  namespace: services
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: ai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendation-sa
  namespace: recommendation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streaming-sa
  namespace: streaming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: amazon-cloudwatch  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streaming-sa
  namespace: streaming