---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: streaming
  labels:
    app: producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      serviceAccountName: streaming-sa
      nodeSelector:
        node-type: streaming
      containers:
        - name: producer
          image: 708778582346.dkr.ecr.us-east-1.amazonaws.com/producer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: streaming
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---