apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onur-master-thesis-app
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yurtseveronr/onur-master-thesis-data
    targetRevision: HEAD
    path: kubernetes_manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10 