apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: gitops


resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml


patchesJson6902:
  - target:
      version: v1
      kind: Namespace
      name: argocd
    patch: |-
      - op: replace
        path: /metadata/name
        value: gitops

  
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: argocd-application-controller
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: gitops
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: gitops
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: argocd-server
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: gitops
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: argocd-applicationset-controller
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: gitops
